### PR TITLE
Use conditional card as wrapper. Fixes issues with cards like history

### LINKED ISSUE #533: Expander-card 2.4.3 : Graph rendering issue
Graphs (type:history-graph & statistics-graph) within expander-card sections are not correctly rendered.

Incorrect : https://ibb.co/sxb41YL

To redraw the graph correctly, unselect and select again one or more series and graph will be rerendered correctly.

After unselect and select a serie: https://ibb.co/TxgrSVh0

Display bug present on Android app and Browser (Brave and Google) on Win11.
Issue is mainly with line-style graphs. Bar graphs seem to be ok.

Downgrading Expander cards to 2.4.2, the rendering issue is not present.
Problem started with 2.4.3 on HA (as vm Proxmox, 8VCPU 16GB Ram), HAOS Core 2025.6.3

Installation method Home Assistant OS
Core 2025.6.3
Supervisor 2025.06.2
Operating System 15.2
Frontend 20250531.4

Steps to reproduce the issue
Sample code :

    title: Garage
    type: custom:expander-card
    cards:
          - chart_type: line
            period: hour
            type: statistics-graph
            entities:
              - entity: sensor.0xa4c138eb9bd52d89_temperature
                name: Ga 1
              - entity: sensor.0xa4c138d40d4b6fe5_temperature
                name: Ga 2
            stat_types:
              - max
            days_to_show: 20
            title: Temperature

Thanks for your help

Th

### PR DESCRIPTION
**Pull request by dcapslock**
Fixes #533

### CODE REVIEW

File: src/configtype.ts [hunk 1]
```diff
@@ -36,4 +36,5 @@ export interface ExpanderConfig {
     'min-width-expanded'?: number;
     'max-width-expanded'?: number;
     icon?: string;
+    'storgage-id'?: string;
```
Comment (dcapslock) [inline src/configtype.ts:39]: Is this actually a typo. I updated types to remove a lint error. Should it actually be 'storage-id' not 'storgage-id'?

File: src/ExpanderCard.svelte [hunk 2]
```diff
@@ -116,7 +116,8 @@
     };
 
     const buttonClickDiv = (event: MouseEvent) => {
-        if (event.currentTarget.classList.contains('title-card-container')) {
+        const target = event.currentTarget as HTMLElement | null;
+        if (target?.classList.contains('title-card-container')) {
```
Comment (dcapslock) [inline src/ExpanderCard.svelte:120]: Updated to remove liniting warnings as currentTarget does not exist on MouseEvent.

File: package.json [hunk 3]
```diff
@@ -17,6 +17,7 @@
     },
     "devDependencies": {
         "@eslint/eslintrc": "^3.3.1",
+        "@eslint/js": "^9.30.1",
```
Comment (dcapslock) [inline package.json:20]: I merged ##542 into my branch so if it is merged first then changes for package.json and pnpm-lock.yaml will not be changes in this PR.

File: src/configtype.ts (hunk 1 above)
Comment (MelleD) [reply src/configtype.ts:39]: Yes I will create a PR for that should be 'storage-id'

**Review by MelleD — APPROVED** [review]

**Comment by MelleD** [comment]
LGTM
