### PR TITLE
fix: expander when used in masonry view may not toggle state.

### LINKED ISSUE #736: Toggle fails when nested in entities card
Thanks for the great card. Since the latest version v3.0.? toggle to expand was broken for me. 
I stripped the cards to the most simplified example:

This works:
``` 
type: custom:expander-card
padding: 0
clear: true
clear-childs: true
title-card-button-overlay: true
title-card-clickable: true
title-card:
  type: markdown
  content: "**Detail**"
cards:
  - type: entities
    entities:
      - sun.sun
expanded: false

``` 

Nested in entities, it fails:
```

type: entities
entities:
  - sun.sun
  - type: custom:expander-card
    padding: 0
    clear: true
    clear-childs: true
    title-card-button-overlay: true
    title-card-clickable: true
    title-card:
      type: markdown
      content: "**Detail**"
    cards:
      - type: entities
        entities:
          - sun.sun
    expanded: false

```

The view jumps back to the top (when it was scrolled down), instead of expanding the nested card

### PR DESCRIPTION
**Pull request by dcapslock**
Fixes #736

### CODE REVIEW

**Comment by dcapslock** [comment]
@MelleD Labeler worked :-) Build CI all good with this PR 🎉

File: src/Card.svelte [hunk 1]
```diff
@@ -89,6 +89,11 @@ limitations under the License.
             el.style.setProperty('--ha-card-backdrop-filter', 'none');
         }
 
+        // eslint-disable-next-line svelte/no-dom-manipulating
+        container.replaceWith(el);
```
Comment (dcapslock) [inline src/Card.svelte:93]: This change prevents a console error by replacing container before calling resizeObserver which may cause a tick to take place and container elemeny may have been removed but svelte not fully updated container binding.

**Comment by MelleD** [comment]
> @MelleD Labeler worked :-) Build CI all good with this PR 🎉

I haven't changed much. I think my GitHub token pool was exhausted from all the testing. 😅

**Review by MelleD — APPROVED** [review]
